version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: notes_app
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - "5434:5432"

  app:
    build: .
    image: note-app
    depends_on:
      - db
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: ${PG_URL}
      SPRING_DATASOURCE_USERNAME: ${PG_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${PG_PASSWORD}
