name: Deploy to EC2

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user/note-app

            # Tạo file .env từ GitHub Secret
            echo "${{ secrets.ENV_FILE_CONTENT }}" > .env

            git pull origin master
            ./mvnw package -DskipTests
            docker build -t note-app .

            docker stop $(docker ps -q --filter ancestor=note-app) || true
            docker run -d -p 8080:8080 note-app
